import { generate } from '.';

describe('generate', () => {
  describe('spec object input', () => {
    it('works', async () => {
      const file = await generate({
        input: {
          components: {
            schemas: {
              ModelOne: {
                properties: {
                  string_field_one: {
                    type: 'string'
                  },
                  string_field_two: {
                    type: 'string'
                  }
                },
                required: ['string_field_one'],
                type: 'object'
              }
            }
          }
        }
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sModelOne = s.object({
  string_field_one: s.string(),
  string_field_two: s.string(),
});
`);
    });
  });
});
