import { generate } from '.';

describe('generate', () => {
  describe('file input', () => {
    it('case: simple', async () => {
      const file = await generate({
        input: './src/sample-specs/simple.json'
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sModelOne = s.object({
  string_field_one: s.string(),
  string_field_two: s.optional(s.string()),
});
`);
    });
    it('case: one-model-all-primitives', async () => {
      const file = await generate({
        input: './src/sample-specs/one-model-all-primitives.json'
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sModelOne = s.object({
  required_string: s.string(),
  required_nullable_string: s.nullable(s.string()),
  optional_string: s.optional(s.string()),
  optional_nullable_string: s.optional(s.nullable(s.string())),
  required_string_date: s.string(),
  required_nullable_string_date: s.nullable(s.string()),
  optional_string_date: s.optional(s.string()),
  optional_nullable_string_date: s.optional(s.nullable(s.string())),
  required_string_date-time: s.string(),
  required_nullable_string_date-time: s.nullable(s.string()),
  optional_string_date-time: s.optional(s.string()),
  optional_nullable_string_date-time: s.optional(s.nullable(s.string())),
  required_string_password: s.string(),
  required_nullable_string_password: s.nullable(s.string()),
  optional_string_password: s.optional(s.string()),
  optional_nullable_string_password: s.optional(s.nullable(s.string())),
  required_string_byte: s.string(),
  required_nullable_string_byte: s.nullable(s.string()),
  optional_string_byte: s.optional(s.string()),
  optional_nullable_string_byte: s.optional(s.nullable(s.string())),
  required_string_binary: s.string(),
  required_nullable_string_binary: s.nullable(s.string()),
  optional_string_binary: s.optional(s.string()),
  optional_nullable_string_binary: s.optional(s.nullable(s.string())),
  required_number: s.number(),
  required_nullable_number: s.nullable(s.number()),
  optional_number: s.optional(s.number()),
  optional_nullable_number: s.optional(s.nullable(s.number())),
  required_number_float: s.number(),
  required_nullable_number_float: s.nullable(s.number()),
  optional_number_float: s.optional(s.number()),
  optional_nullable_number_float: s.optional(s.nullable(s.number())),
  required_number_double: s.number(),
  required_nullable_number_double: s.nullable(s.number()),
  optional_number_double: s.optional(s.number()),
  optional_nullable_number_double: s.optional(s.nullable(s.number())),
  required_integer: s.integer(),
  required_nullable_integer: s.nullable(s.integer()),
  optional_integer: s.optional(s.integer()),
  optional_nullable_integer: s.optional(s.nullable(s.integer())),
  required_integer_int32: s.integer(),
  required_nullable_integer_int32: s.nullable(s.integer()),
  optional_integer_int32: s.optional(s.integer()),
  optional_nullable_integer_int32: s.optional(s.nullable(s.integer())),
  required_integer_int64: s.integer(),
  required_nullable_integer_int64: s.nullable(s.integer()),
  optional_integer_int64: s.optional(s.integer()),
  optional_nullable_integer_int64: s.optional(s.nullable(s.integer())),
  required_boolean: s.boolean(),
  required_nullable_boolean: s.nullable(s.boolean()),
  optional_boolean: s.optional(s.boolean()),
  optional_nullable_boolean: s.optional(s.nullable(s.boolean())),
});
`);
    });
    it('case: one-model-complex-types', async () => {
      const file = await generate({
        input: './src/sample-specs/one-model-complex-types.json'
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sModelOne = s.object({
  required_array<string>: s.array(s.string()),
  required_nullable_array<string>: s.nullable(s.array(s.string())),
  optional_array<string>: s.optional(s.array(s.string())),
  optional_nullable_array<string>: s.optional(s.nullable(s.array(s.string()))),
  required_array<nullable_string>: s.array(s.nullable(s.string())),
  deeply_nested_array: s.optional(s.array(s.array(s.array(s.integer())))),
  required_object: s.object({
    nested_required_string: s.string(),
    nested_optional_nullable_integer: s.optional(s.nullable(s.integer())),
    nested_required_array<boolean>: s.array(s.boolean()),
    nested_required_object: s.object({
      doubly_nested_required_string: s.string(),
    }),
  }),
});
`);
    });
    it('case: multiple-models-top-level-primitives', async () => {
      const file = await generate({
        input: './src/sample-specs/multiple-models-top-level-primitives.json'
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sString = s.string()
export const sNullable_string_date = s.nullable(s.string())
export const sString_date-time = s.string()
export const sNullable_string_password = s.nullable(s.string())
export const sString_byte = s.string()
export const sNullable_string_binary = s.nullable(s.string())
export const sNumber = s.number()
export const sNullable_number_float = s.nullable(s.number())
export const sNumber_double = s.number()
export const sNullable_integer = s.nullable(s.integer())
export const sInteger_int32 = s.integer()
export const sNullable_integer_int64 = s.nullable(s.integer())
export const sBoolean = s.boolean()
`);
    });
  });
  describe('object input', () => {
    it('case: simple', async () => {
      const file = await generate({
        input: {
          components: {
            schemas: {
              ModelOne: {
                properties: {
                  string_field_one: {
                    type: 'string'
                  },
                  string_field_two: {
                    type: 'string'
                  }
                },
                required: ['string_field_one'],
                type: 'object'
              }
            }
          }
        }
      });
      expect(file).toEqual(`/* autogenerated by openapi-superstruct */

import * as s from 'superstruct';

export const sModelOne = s.object({
  string_field_one: s.string(),
  string_field_two: s.optional(s.string()),
});
`);
    });
  });
});
